#!/usr/bin/env bash
# redirect to youtube video
REDIR="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/;\n\}"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
sed -i "/server {/i $REDIR" "$FILE"
service nginx restart
