#!/usr/bin/env bash
# FIZZYBUZZY

count=1
while [ $count -le 100 ]
do
	if (($count % 3 == 0)) && (($count % 5 == 0))
	then
		echo "FizzBuzz"
	elif (($count % 3 == 0))
	then
		echo "Fizz"
	elif (($count % 5 == 0))
	then
		echo "Fizz"
	else
		echo "$count"
	fi
	((count++))
done