#!/usr/bin/env bash
#script run as nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
